//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cv_Asp.net.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Hakkımda
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string SoyAd { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string Acıklama { get; set; }
        public string Resim { get; set; }
    }
}
