//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cv_Asp.net.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Hobiler
    {
        public int ID { get; set; }
        public string Acıklama1 { get; set; }
        public string Acıklama2 { get; set; }
    }
}
